[build]
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://rentalbackend-x86y.onrender.com/api"
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 